name: id
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_screen_images/
    - assets/logo/
    - assets/logo/logo.png
