name: id
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  intl: ^0.20.2
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  logger: ^2.5.0
  google_fonts: ^6.2.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.1.2
  #loading_animation_widget: ^1.3.0

  #Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1

  #facilitator
  bottom_picker: ^2.10.1
  flutter_otp_text_field: ^1.4.0+2
  syncfusion_flutter_calendar: ^28.1.36

  # State Management
  get_storage: ^2.1.1
  get: ^4.6.6

  #icon
  flutter_launcher_icons: ^0.14.3
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_screen_images/
    - assets/images/forgot_password_images/
    - assets/logo/
    - assets/images/teacher_screen_images/
    - assets/logo/logo.png
    - assets/logo/logos.png
    - assets/images/bottom_nav_bar_images/
    - assets/animations/loading.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
