name: id
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  icons_plus: ^5.0.0
  flutter_otp_text_field: ^1.4.0+2
  syncfusion_flutter_calendar: ^28.1.36
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  bottom_picker: ^2.10.1
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_screen_images/
    - assets/images/forgot_password_images/
    - assets/logo/
    - assets/images/teacher_screen_images/
    - assets/logo/logo.png
    - assets/logo/logos.png
    - assets/images/bottom_nav_bar_images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
