// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBS0fIlkkTelaRsHfnouRJh1WKMa5sty8',
    appId: '1:394722127903:web:6dd567e5a3a5c4f705252a',
    messagingSenderId: '394722127903',
    projectId: 'id-project-hilcoe',
    authDomain: 'id-project-hilcoe.firebaseapp.com',
    storageBucket: 'id-project-hilcoe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcP24zgE2uozePYeaV-Lvo9mHW7B56Mg',
    appId: '1:394722127903:android:651d2b1699d7a38205252a',
    messagingSenderId: '394722127903',
    projectId: 'id-project-hilcoe',
    storageBucket: 'id-project-hilcoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFtmrB2gMomJNKduJjT-LrEO_wXWI68A',
    appId: '1:394722127903:ios:780c06663286f26905252a',
    messagingSenderId: '394722127903',
    projectId: 'id-project-hilcoe',
    storageBucket: 'id-project-hilcoe.firebasestorage.app',
    iosBundleId: 'com.example.id',
  );
}
